# Generated by Django 4.0.5 on 2022-07-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateTimeField(auto_created=True, blank=True)),
                ('subject', models.CharField(choices=[('OR', 'Order'), ('R', 'Return'), ('D', 'Delivery')], help_text='Required', max_length=255, verbose_name='subject choice')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('message', models.TextField()),
                ('img', models.ImageField(blank=True, height_field=150, upload_to='images', verbose_name='Image', width_field=200)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
