# Generated by Django 4.1 on 2022-08-08 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('בנית אתרים', 'בנית אתרים'), ('שיעורים פרטיים', 'שיעורים פרטיים'), ('דפי מידע', 'דפי מידע')], max_length=255, verbose_name='בחירת נושא')),
                ('name', models.CharField(max_length=250, verbose_name='שם מלא')),
                ('email', models.EmailField(max_length=254, verbose_name='אמייל')),
                ('title', models.CharField(max_length=250, verbose_name='כותרת')),
                ('message', models.TextField(verbose_name='הודעה')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='פלפון/טלפון')),
                ('files', models.FileField(blank=True, upload_to='files_contact/', verbose_name='קובץ')),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
