# Generated by Django 4.0.5 on 2022-07-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_send',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
