# Generated by Django 4.0.5 on 2022-07-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_contact_date_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=321, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=324, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('OR', 'Order'), ('R', 'Return'), ('D', 'Delivery')], max_length=255, verbose_name='subject choice'),
        ),
    ]
