# Generated by Django 4.0.5 on 2022-07-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_contact_email_contact_name_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Order', 'Order'), ('Return', 'Return'), ('Delivery', 'Delivery')], max_length=255, verbose_name='subject choice'),
        ),
    ]
