# Generated by Django 4.1 on 2022-08-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=1, max_length=10, verbose_name='פלפון/טלפון'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='אמייל'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='img',
            field=models.ImageField(blank=True, height_field=150, upload_to='images', verbose_name='קובץ', width_field=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='הודעה'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=250, verbose_name='שם מלא'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('בנית אתרים', 'בנית אתרים'), ('שיעורים פרטיים', 'שיעורים פרטיים'), ('דפי מידע', 'דפי מידע')], max_length=255, verbose_name='בחירת נושא'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=250, verbose_name='כותרת'),
        ),
    ]
