# Generated by Django 4.1 on 2022-08-08 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_contact_phone_alter_contact_email_alter_contact_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator], verbose_name='פלפון/טלפון'),
        ),
    ]
