# Generated by Django 4.1 on 2022-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='פלפון/טלפון'),
        ),
    ]
