# Generated by Django 4.1 on 2022-08-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='img',
        ),
        migrations.AddField(
            model_name='contact',
            name='files',
            field=models.FileField(blank=True, upload_to='media/', verbose_name='קובץ'),
        ),
    ]
