# Generated by Django 4.1 on 2022-08-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_remove_contact_img_contact_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, upload_to='Example/')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='files',
            field=models.FileField(blank=True, upload_to='files_contact/', verbose_name='קובץ'),
        ),
    ]
