# Generated by Django 4.1 on 2022-08-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_examplemodel_alter_contact_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
