# Generated by Django 4.1 on 2022-08-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_delete_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, upload_to='Example/')),
                ('slug', models.SlugField()),
                ('url', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
