# Generated by Django 4.1 on 2022-08-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_examplemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='slug_auto',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
