# Generated by Django 4.1 on 2022-08-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_remove_examplemodel_slug_examplemodel_slug_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplemodel',
            old_name='slug_auto',
            new_name='slug',
        ),
    ]
