# Generated by Django 4.1 on 2022-08-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0017_remove_examplemodel_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
