# Generated by Django 4.1 on 2022-08-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='detail',
        ),
    ]
