# Generated by Django 4.1 on 2022-08-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/media/example/'),
        ),
    ]
