# Generated by Django 4.1 on 2022-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_alter_examplemodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='Example/'),
        ),
    ]
