# Generated by Django 4.1 on 2022-08-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_remove_servicemodel_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_masthead', models.CharField(max_length=255)),
                ('description_masthead', models.CharField(max_length=555)),
                ('title_service', models.CharField(max_length=255)),
                ('title_about', models.CharField(max_length=255)),
                ('description_about', models.CharField(max_length=555)),
            ],
        ),
    ]
