# Generated by Django 4.1 on 2022-08-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_indexpagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
