# Generated by Django 4.1 on 2022-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_alter_examplemodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_view', models.PositiveIntegerField()),
                ('home_view_week', models.PositiveIntegerField()),
            ],
        ),
    ]
