# Generated by Django 4.1 on 2022-08-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_indexpagemodel_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
