# Generated by Django 4.1 on 2022-08-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_alter_examplemodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='img',
            field=models.ImageField(blank=True, height_field='avatar_height', upload_to='images/', width_field='avatar_width'),
        ),
    ]
