# Generated by Django 4.1 on 2022-08-15 20:07

from django.db import migrations, models
import django_imgur.storage


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_satisticmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='satisticmodel',
            name='home_view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='satisticmodel',
            name='home_view_week',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
