# Generated by Django 4.1 on 2022-08-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0005_indexpagemodel_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='button_befor_fotter',
            field=models.CharField(default=654, max_length=555),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='title_befor_fotter',
            field=models.CharField(default=6547, max_length=255),
            preserve_default=False,
        ),
    ]
