# Generated by Django 4.1 on 2022-08-08 13:14

from django.db import migrations
import view.models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0006_indexpagemodel_button_befor_fotter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpagemodel',
            name='date_create',
            field=view.models.CustomDateTimeField(auto_now_add=True),
        ),
    ]
