# Generated by Django 4.1 on 2022-08-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0007_alter_indexpagemodel_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpagemodel',
            name='description_about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indexpagemodel',
            name='description_masthead',
            field=models.TextField(),
        ),
    ]
