# Generated by Django 4.1 on 2022-08-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0010_examplemodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255)),
        ),
    ]
