# Generated by Django 4.1 on 2022-08-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0011_alter_examplemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='slug_auto',
            field=models.SlugField(default=54),
            preserve_default=False,
        ),
    ]
