# Generated by Django 4.1 on 2022-08-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0012_remove_examplemodel_slug_examplemodel_slug_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='slug_auto',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='url',
        ),
    ]
