# Generated by Django 4.1 on 2022-08-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0013_remove_examplemodel_slug_auto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
