# Generated by Django 4.1 on 2022-08-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0014_examplemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
