# Generated by Django 4.1 on 2022-08-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0016_remove_examplemodel_slug_examplemodel_slug_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
