# Generated by Django 4.1 on 2022-08-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0017_examplemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='slug',
        ),
    ]
